### ISSUE TITLE
Spatial Sound in Unity Microsoft.SpatialAudio.Spatializer.Unity Requires Dependencies

### ISSUE THREAD

**Issue by kathleenwest** [microsoft/spatialaudio-unity#12]
I think the documentation [here: https://docs.microsoft.com/en-us/windows/mixed-reality/spatial-sound-in-unity] should be updated to include any required dependencies that the user needs to install. I thought this plugin was independent.

Got this error:
Plugins: Failed to load 'Assets/Packages/Microsoft.SpatialAudio.Spatializer.Unity.1.0.0/Plugins/x86_64/AudioPluginMicrosoftSpatializer.dll' because one or more of its dependencies could not be loaded.

**Comment by MikeChemi** [comment]
Hi @kathleenwest, can you share some more information about your setup? In particular, I'm interested in:
- Which version of Windows are you using?
- Which Unity version are you using?
- Do you have Visual Studio installed? If so, which edition?

**Comment by kathleenwest** [comment]
_Which version of Windows are you using?_ Windows 10 Pro Version 1909 OS build 18363.720
_Which Unity version are you using?_ Project is running on Unity 2019.3.2f1
_Do you have Visual Studio installed?_ _If so, which edition?_ Yes, although I was not using/running VS at the time of the plugin install... my version is Visual Studio 2017 Enterprise Version 15.9.21

**Comment by MikeChemi** [comment]
OK, weird. We also expect the plugin to be fully independent, especially with your setup. Let's try to get to the bottom of this. Having Visual Studio installed should also include the VC Runtime redistributables, but perhaps those are missing? You can try to install the latest from here https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by kathleenwest** [comment]
My VS Enterprise is fully up-to-date and customized to my needs. I am not installing that item you posted. As previously mentioned, the error issue is found in _Unity_, not Visual Studio. Today I went ahead and created a clean project with no game objects and first installed the NuGet package, then searched, downloaded, and installed the _Microsoft.SpatialAudio.Spatializer.Unity_ from NuGet. I got the same errors and something else that may help the project developers. Please now go ahead and try this yourself to verify the issue.

Plugins: Failed to load 'Assets/Packages/Microsoft.SpatialAudio.Spatializer.Unity.1.0.0/Plugins/x86_64/AudioPluginMicrosoftSpatializer.dll' because one or more of its dependencies could not be loaded.
UnityEditor.AssetDatabase:Refresh()
NugetForUnity.NugetHelper:Install(NugetPackage, Boolean)
NugetForUnity.NugetHelper:InstallIdentifier(NugetPackageIdentifier, Boolean)
NugetForUnity.NugetWindow:DrawPackage(NugetPackage, GUIStyle, GUIStyle)
NugetForUnity.NugetWindow:DrawPackages(List`1)
NugetForUnity.NugetWindow:DrawOnline()
NugetForUnity.NugetWindow:OnGUI()
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Plugins: Failed to load 'Assets/Packages/Microsoft.SpatialAudio.Spatializer.Unity.1.0.0/Plugins/x86_64/AudioPluginMicrosoftSpatializer.dll' because one or more of its dependencies could not be loaded.

**Comment by MikeChemi** [comment]
We have tested this plugin extensively and have never hit the issue you describe. Unfortunately, there are many reasons why a dependency may be missing, and tracking down dependency issues can be challenging. I understand that Unity is giving the error, and my comments about Visual Studio were only to say that often the VC Runtime is installed as part of Visual Studio, but not always (I believe it is an optional component).

Given your setup and the dependencies I know about for this plugin, I suspect this is a case of a missing VC Runtime on your PC (which can affect plugins loading Unity). For more information on the VC Runtime, please see the main page for downloading the redistributable https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by kathleenwest** [comment]
![install](https://user-images.githubusercontent.com/28828668/76652230-8f02f400-653c-11ea-872f-e20a6442e9f0.jpg)
 attached is a picture to prove this was already installed. I have like 10+ versions of this as it is pretty standard... and it has been updated. what's next ?

**Comment by kathleenwest** [comment]
So did you try testing this plugin 1.) recently within the past 5 days 2.) in a unity 3D project and 3.) download and installing it from NuGet (which may be the issue?).

**Comment by MikeChemi** [comment]
Yep! I tried this out when you reported it to be sure nothing had changed on our end. Thanks for sharing the picture of the VC Runtimes you have installed. I, too, have a lot of them. Do you also have this one? 
![image](https://user-images.githubusercontent.com/1040735/76652617-332c7100-6524-11ea-8d50-8296cb4b3293.png)
I uninstalled this one, and was finally able to reproduce the error on my PC:
![image](https://user-images.githubusercontent.com/1040735/76652779-84d4fb80-6524-11ea-8090-c4faa866c23d.png)

**Comment by MikeChemi** [comment]
I closed Unity, re-installed from the link I shared previously, restarted Unity, and the error is now gone.

**Comment by kathleenwest** [comment]
I'm still very hesitant/concerned to install this because of this disclaimer on the site as it could affect programs built with other C++ installs. Feedback: I'd like to see this Unity plug-in compatible/dependent on the standard/common C++ redistributable option in Visual Studio (2017) installer or what is included with the standard/common Windows Update C++ Redistributable package and not on a mashup that has some potential issues with compatibilities as noted in the link and below. 

_Note Visual C++ 2015, 2017 and 2019 all share the same redistributable files.

For example, **installing the Visual C++ 2019 redistributable will affect programs built with Visual C++ 2015 and 2017 also.** However, installing the Visual C++ 2015 redistributable will not replace the newer versions of the files installed by the Visual C++ 2017 and 2019 redistributables.

This is different from all previous Visual C++ versions, as they each had their own distinct runtime files, not shared with other versions._

**Comment by MikeChemi** [comment]
Sure, that's your prerogative. The shared VC Redist is the officially supported way to dynamically link to the VC Runtime moving forward, not a random mashup that we decided to use. If your use case requires linking an older version of the VC Runtime, feel free to clone the repo and retarget the solution to VS 2017. This is a good page that discusses this shared runtime usage https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=vs-2019

**Comment by MikeChemi** [comment]
In the meantime, I'll see about adding a blurb about the required VC Runtime version to our documentation.

**Comment by MikeChemi** [comment]
PR submitted on the docs to point out this dependency.
