### ISSUE TITLE
v1.0.36 isn't available in the Github releases page but is available on Nuget.

### ISSUE THREAD

**Issue by itadakimasu** [microsoft/spatialaudio-unity#32]
Latest release on Nuget is v.1.0.36: https://www.nuget.org/packages/Microsoft.SpatialAudio.Spatializer.Unity/
Latest release on Github is v1.0.18: https://github.com/microsoft/spatialaudio-unity/releases

Is Nuget the direction that this project is heading? It would be great if the Unity packages could be kept in lock-step

**Comment by ashtat** [comment]
Hi @itadakimasu, thanks for logging this issue. Completely agree that it would be great to keep all packages everywhere in lock-step. This is a slip up on our part while we're working on bringing up a UPM feed (Nuget packages are getting pushed in the CI build while GitHub releases are not automated). We will fix this asap.

**Comment by ashtat** [comment]
Thanks again for the report @itadakimasu. Fixed with the latest release.
