### ISSUE TITLE
Unity app crashes at invalid_pointer_read_c0000005_audiopluginmicrosoftspatializer.dll!unitygetaudioeffectdefinitions

### ISSUE THREAD

**Issue by binxie33** [microsoft/spatialaudio-unity#55]
We publish a Hololens2 Unity app that uses Microsoft audio spatializer. And in the device portal, we receives many reports about application crashes at **invalid_pointer_read_c0000005_audiopluginmicrosoftspatializer.dll!unitygetaudioeffectdefinitions**. The following is the callstack (not very helpful since it has no symbol)

![Capture](https://user-images.githubusercontent.com/35978406/122496501-770eff80-d01e-11eb-9ab2-be73067d0be1.PNG)

Any ideas how to resolve the problem?

**Comment by ashtat** [comment]
Hi @binxie33, sorry about this, our [latest release](https://github.com/microsoft/spatialaudio-unity/releases/tag/v1.0.196) includes symbols. Would it be possible for you to switch over to this version?

**Comment by binxie33** [comment]
hi @ashtat, we are already using the latest build when the above screenshot is captured, and still no symbol for the callstacks

**Comment by ashtat** [comment]
Do you know if the PDB included with the unity plugin is deployed to the device?

**Comment by binxie33** [comment]
i check the project and found the pdb files are not included. We will include them in the next release.

**Comment by ashtat** [comment]
@binxie33 let us know if this is still an issue. Closing for now.
