### ISSUE TITLE
Incorrect plugin import settings for standalone x86_64

### ISSUE THREAD

**Issue by Daniel4144** [microsoft/spatialaudio-unity#83]
In the latest version 2.0.37 the import settings for x86_64 HrtfDsp.dll are not configured correctly - x64 should be checked in Platform settings for standalone builds. At the moment both available options (x86, x64) are unchecked.

**Comment by NoelCross** [comment]
@Daniel4144 Thank you for reporting this issue.  We'll file a bug report in our internal database and make this change when we release the next update.
