### ISSUE TITLE
Missing mainfast?

### ISSUE THREAD

**Issue by nirharpaz** [microsoft/spatialaudio-unity#87]
When I try to add the code into unity via package manager and the git link I receive this error

[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/microsoft/spatialaudio-unity.git]:
  [https://github.com/microsoft/spatialaudio-unity.git] does not point to a valid package. No package manifest was found. [NotFound].

I'm using Windows 11 and unity 2021.2.19

**Comment by NoelCross** [comment]
@nirharpaz if you are trying to integrate the package into your project, the easiest way to do this is by following the instructions for acquiring packages via the [Mixed Reality Feature Tool](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/configuration/usingupm?view=mrtkunity-2021-05).  The link that you provided for the Unity package manager is the link to the source code for this repo which won't get the spatialaudio package integrated into your project.

**Comment by nirharpaz** [comment]
Thank you,
I've tested your advice and it worked
